### ISSUE TITLE
JavaScript errors

### ISSUE THREAD

**Issue by RinkAttendant6** [grid-js/website#4]
The website has JavaScript errors on the documentation pages which make it impossible to open collapsed menus to navigate (amongst other behaviour)

Browsers affected: Firefox 75, Microsoft Edge 44
URL: https://gridjs.io/docs/index/

Noting that it works fine in Chrome and I assume other Chromium-based browsers such as new Edge.

**Comment by afshinm** [comment]
Thanks @RinkAttendant6, those errors will be fixed soon.
